spring.application.name=sbb

spring.devtools.livereload.enabled=true
spring.devtools.restart.enabled=true

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true

# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true


#log level
logging.level.jdbc.sqlonly=off
logging.level.jdbc.sqltiming=debug
logging.level.jdbc.audit=off
logging.level.jdbc.resultset=off
logging.level.jdbc.resultsettable=off
logging.level.jdbc.connection=off
logging.level.root=info

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=60MB
spring.servlet.multipart.resolve-lazily=true
