spring.application.name=sbb

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.check-template-location=true

server.port=8080

# DATABASE ??
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/test_v2?autoReconnect=true&allowMultiQueries=true
spring.datasource.username=root
spring.datasource.password=wpaxprmsg098


# DATABASE  ??
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://localhost:3306/testdb?autoReconnect=true&allowMultiQueries=true
#spring.datasource.username=naneetest
#spring.datasource.password=bong1221


# JPA
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL57Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true